### ISSUE TITLE
Iteration in templates/rss.j2 does not work

### ISSUE THREAD

**Issue by ghost** [kalliope-project/kalliope_neuron_rss_reader#1]
Iteration in templates/rss.j2 like
``` 
{% set count = 1 %} 
{% for item in items %} 
   {{ count }} ...
   {% set count = count + 1 %} 
{% endfor %} 
```
does not work properly here but 

```
{% set count = 1 %}
{% for item in items %}
    {{ loop.index }} ...
{% endfor %}
```

**Comment by royto** [comment]
Hi @1account , I just test this tempates and its works for me

```{% set count = 1 %} 
{% for item in items %} 
   {{ count }} 
   {% set count = count + 1 %} 
{% endfor %} ``` 

What is your error / issue ?

What are the version used for python, kalliope, jinja ?

**Comment by Sispheor** [comment]
Seems to be the right way to do it indeed.
This is how we do usually anyway.
https://stackoverflow.com/questions/7537439/how-to-increment-a-variable-on-a-for-loop-in-jinja-template

**Comment by ghost** [comment]
I totally forgot about this issue. I will not dive into it but you can get an idea of it below and there is a final conclusion from one developer here

https://github.com/pallets/jinja/issues/641
